FROM guacamole/guacamole
COPY server.xml /usr/local/tomcat/conf/server.xml
FROM guacamole/guacamole
COPY server.xml /usr/local/tomcat/conf/server.xml
FROM guacamole/guacamole
COPY server.xml /usr/local/tomcat/conf/server.xml
